@endpoint=http://localhost:{{$dotenv PORT}}/api

### Erreur 404
GET {{endpoint}}/notfound

### Documentation
GET {{endpoint}}-docs

### Recuperer une partie
GET {{endpoint}}/game/1

### Créer une partie
POST {{endpoint}}/game
Content-Type: application/json

{
    "name": "Le vol des dragons",
    "licence": "Donjons et dragons"
}